spring.application.name=event-booking

# Server
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/event_booking_db
spring.datasource.username=root
spring.datasource.password=admin1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=ZXZlbnRib29raW5nX3NlY3JldF9rZXlfZm9yX2p3dF8yMDI0
jwt.expiration=1800000

# Logging
logging.level.com.tulika.eventbooking=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n