spring.application.name=event-booking
# Server
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/event_booking_db
spring.datasource.username=root
spring.datasource.password=admin1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=your_super_secret_key_must_be_32_chars_min
jwt.expiration=1800000

# Logging
logging.level.com.eventbooking=DEBUG
logging.level.org.springframework.security=INFO