"""
Generator examples.
"""
def get_positive_integer(prompt: str) -> int:
    """
    Get a valid positive integer from the user.
    """
    while True:
        try:
            value = int(input(prompt))

            if value <= 0:
                print("Please enter a positive integer.")
                continue

            return value

        except ValueError:
            print("Please enter a valid integer.")


# Question 3: Create a generator that yields square numbers up to N.

def square_generator(limit: int):
    """
    Generate square numbers up to N.
    """
    for number in range(1, limit + 1):
        yield number ** 2

# Question 4: Create a generator that yields Fibonacci numbers up to N.
def fibonacci_generator(limit: int):
    """
    Generate Fibonacci numbers.
    """
    first_number = 0
    second_number = 1

    for _ in range(limit):
        yield first_number
        first_number, second_number = (
            second_number,
            first_number + second_number
        )

# Question 5: Create a generator expression that yields even numbers from 1 to 50.
from typing import Generator
def generate_even_numbers() -> Generator[int, None, None]:
    """
    Generate even numbers from 1 to 50 using a generator expression.
    """
    return (
        number
        for number in range(1, 51)
        if number % 2 == 0
    )

# Question 7: Process a large dataset using a generator.
def large_dataset_generator(limit: int):
    """
    Simulate processing a large dataset using a generator.

    Args:
        limit (int): Number of records.
    """
    for number in range(limit):
        yield number

# Question 7: Process a large dataset using a generator.
def large_dataset_generator(limit: int) -> Generator[int, None, None]:
    """
    Simulate processing a large dataset by generating
    records one at a time instead of storing all records
    in memory.

    Args:
        limit (int): Number of records to generate.

    Yields:
        int: Individual record.
    """
    for record_id in range(1, limit + 1):
        yield record_id


def process_large_dataset(limit: int) -> None:
    """
    Process records generated by a generator.

    Args:
        limit (int): Number of records to process.
    """
    for record in large_dataset_generator(limit):
        print(f"Processing record {record}")


if __name__ == "__main__":
    limit = get_positive_integer("Enter the limit: ")

    for square in square_generator(limit):
        print(square)

    print("\n--- Question 4 ---")
    limit = get_positive_integer("How many Fibonacci numbers do you want? ")

    for number in fibonacci_generator(limit):
        print(number)

    print("\n--- Question 5 ---")
    for number in generate_even_numbers():
        print(number)
    
    print("\n--- Question 7 ---")

    dataset_size = get_positive_integer("Enter dataset size: ")

    process_large_dataset(dataset_size)